# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('name', models.TextField(blank=True, choices=[('computer', 'Computer'), ('phone', 'Phone'), ('software', 'Software'), ('car', 'Car'), ('rocket', 'Rocket')], null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('maintenance_notes', models.TextField(blank=True, null=True)),
                ('date_acquired', models.DateField(blank=True, default='2017-11-19', null=True, verbose_name='date acquired')),
                ('date_implemented', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('role', models.TextField(blank=True, choices=[('admin', 'Admin'), ('manager', 'Manager'), ('employee', 'Employee')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_location', models.TextField(blank=True, choices=[('San Jose', 'San Jose, CA, USA'), ('Los Angeles', 'Los Angeles, CA, USA'), ('Denver', 'Denver, CO, USA'), ('Madrid', 'Madrid, Spain'), ('Paris', 'Paris, FrancLe'), ('Beijing', 'Beijing, China')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, choices=[('Dell', 'Dell'), ('Apple', 'Apple'), ('Tesla', 'Tesla'), ('SpaceX', 'SpaceX'), ('Microsoft', 'Microsoft')], null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, choices=[('MO', 'MyOrg'), ('EO', 'ExampleOrg')], null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='employee',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='asset_management.Employee'),
        ),
        migrations.AddField(
            model_name='asset',
            name='location',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='asset_management.Location'),
        ),
        migrations.AddField(
            model_name='asset',
            name='manufacturer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='asset_management.Manufacturer'),
        ),
        migrations.AddField(
            model_name='asset',
            name='organization',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='asset_management.Organization'),
        ),
    ]
