# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.TextField(blank=True, choices=[('computer', 'Computer'), ('phone', 'Phone'), ('software', 'Software'), ('car', 'Car'), ('rocket', 'Rocket')], null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.TextField(blank=True, choices=[('SJ', 'San Jose, CA, USA'), ('LA', 'Los Angeles, CA, USA'), ('D', 'Denver, CO, USA'), ('M', 'Madrid, Spain'), ('P', 'Paris, FrancLe'), ('B', 'Beijing, China')], null=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.TextField(blank=True, choices=[('Dell', 'Dell'), ('Apple', 'Apple'), ('Tesla', 'Tesla'), ('SpaceX', 'SpaceX'), ('Microsoft', 'Microsoft')], null=True),
        ),
    ]
