# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0002_auto_20171120_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='date_acquired',
            field=models.TextField(blank=True, default='July, 2000', null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='tag',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
