# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 17:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0002_auto_20171120_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='tag',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 10 characters', regex='^.{10}$')]),
        ),
    ]
