# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0003_auto_20171120_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.TextField(blank=True, choices=[('admin', 'Admin'), ('manager', 'Manager'), ('employee', 'Employee')], null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.TextField(blank=True, choices=[('San Jose', 'San Jose, CA, USA'), ('Los Angeles', 'Los Angeles, CA, USA'), ('Denver', 'Denver, CO, USA'), ('Madrid', 'Madrid, Spain'), ('Paris', 'Paris, FrancLe'), ('Beijing', 'Beijing, China')], null=True),
        ),
    ]
