# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0003_auto_20171120_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='part_number',
            field=models.TextField(blank=True, null=True),
        ),
    ]
